### ISSUE TITLE
Missing files, How to solve it? 

### ISSUE THREAD

**Issue by awk333** [uber-research/jpeg2dct#18]
Traceback (most recent call last):
  File "D:\Anaconda3\lib\distutils\_msvccompiler.py", line 408, in compile
    self.spawn(args)
  File "D:\Anaconda3\lib\distutils\_msvccompiler.py", line 514, in spawn
    return super().spawn(cmd)
  File "D:\Anaconda3\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "D:\Anaconda3\lib\distutils\spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DCT code\jpeg2dct\setup.py", line 270, in build_extensions
    abi_compile_flags = build_tf_extension(self, options)
  File "D:\DCT code\jpeg2dct\setup.py", line 255, in build_tf_extension
    build_ext.build_extension(tf_lib)
  File "D:\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\Anaconda3\lib\distutils\_msvccompiler.py", line 410, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

building 'jpeg2dct.common.common_lib' extension
creating build\temp.win-amd64-3.9\Release\jpeg2dct\common
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda3\include -ID:\Anaconda3\include -ID:\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /EHsc /Tpjpeg2dct/common/dctfromjpg.cc /Fobuild\temp.win-amd64-3.9\Release\jpeg2dct/common/dctfromjpg.obj -std=c++11 -fPIC -O2 /c /nologo /Ox /W3 /GL /DNDEBUG /MD
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
cl : Command line warning D9002 : ignoring unknown option '-fPIC'
dctfromjpg.cc
jpeg2dct/common/dctfromjpg.cc(16): fatal error C1083: Cannot open include file: 'jpeglib.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

**Comment by acerhp** [comment]
Can you solve this problem?

**Comment by 86236291** [comment]
I have the same problem. I need some help
